"""empty message

Revision ID: 67be2809bf26
Revises: 2aed1f6be306
Create Date: 2020-12-31 08:06:36.634616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67be2809bf26'
down_revision = '2aed1f6be306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
